### ISSUE TITLE
Allow per-request adjustment of limits

### ISSUE THREAD

**Issue by damianh** [damianh/LimitsMiddleware#1]
Should be able to do per-request adjustment of limits. 

I don't think I want to expose the environment dictionary to the user, but a readonly interface of some sort. Something like:

```
builder.MaxConcurrentRequests(request => request.PathBase.StartsWith("/restricted", StringComparison.OrdinalIgnoreCase) ? 10000 : int.MaxValue)
```

**Comment by thefringeninja** [comment]
I'm assuming ATM that MaxQueryStringLength and MaxUrlLength do not need this functionality.

**Comment by damianh** [comment]
Yes, this wouldn't make sense there.
