### ISSUE TITLE
Doc for MinResponseDelay() was copied from MaxBandwidthPerRequest()

### ISSUE THREAD

**Issue by abatishchev** [damianh/LimitsMiddleware#27]
[Xml doc for `public static IAppBuilder MinResponseDelay()`](https://github.com/damianh/LimitsMiddleware/blob/master/src/LimitsMiddleware.OwinAppBuilder/AppBuilderExtensions.MinResponseDelay.cs#L13)) currently is:

>
        /// <param name="minDelay">
        ///     The maximum number of bytes per second to be transferred. Use 0 or a negative
        ///     number to specify infinite bandwidth.
        /// </param>

which seems to be a copy of [one for` public static IAppBuilder MaxBandwidthPerRequest()`](https://github.com/damianh/LimitsMiddleware/blob/master/src/LimitsMiddleware.OwinAppBuilder/AppBuilderExtensions.MaxBandwidthPerRequest.cs#L13):

>
        /// <param name="maxBytesPerSecond">
        ///     The maximum number of bytes per second to be transferred. Use 0 or a negative
        ///     number to specify infinite bandwidth.
        /// </param>

**Comment by abatishchev** [comment]
Bump?

**Comment by damianh** [comment]
oops yeah

**Comment by damianh** [comment]
Fixed with a yolo commit. Will be in next release.
