### ISSUE TITLE
Support aspnetcore

### ISSUE THREAD

**Issue by lvermeulen** [damianh/LimitsMiddleware#28]
@damianh I would like to make an aspnetcore version of your middleware. A PR would be quite traumatic, while at the same time I feel like an aspnetcore version should still be connected to this repo. How would you prefer I proceed?

**Comment by damianh** [comment]
Hi @lvermeulen , thank you for reaching out.

Yes, a PR here would be traumatic. I think I'll like to leave this repo remain OWIN focused. So please be my guest to do an aspnetcore version of this in your own repo copying what you want however you want it. 

As this is MIT licensed, so you don't have to do anything I ask except [follow the terms of the  licence](http://softwareengineering.stackexchange.com/a/178493). Other than that, a link back to this repo in your repo's `readme.md` would be appreciated.

OSS is great, fork, modify and go forth :)

**Comment by lvermeulen** [comment]
Hi @damianh I will proceed and naturally include the appropriate mentions. Thank you very much!
