### ISSUE TITLE
Logs added even if no logger set

### ISSUE THREAD

**Issue by mskvorcovs** [damianh/LimitsMiddleware#29]
I'm setting 
`appBuilder.MaxRequestContentLength(1024*Utils.MaxRequestSizeKb, null); //x1024 for kilobytes`
But still my log is flooded with messages like:

> 2017-10-18 13:53:23,677 - Max valid content length is 51322880.
> 2017-10-18 13:53:23,677 - Not a chunked request. Checking content length header.
> 2017-10-18 13:53:23,677 - Content length header check passed.
> 2017-10-18 13:53:23,677 - Request body stream configured with length limiting stream of 51322880.
> 2017-10-18 13:53:23,677 - Request forwarded.

These lines are added for each request.

**Comment by damianh** [comment]
This project uses [LibLog](https://github.com/damianh/LibLog). Logging will be automatically wired up. Those log messages are at [debug leve](https://github.com/damianh/LimitsMiddleware/blob/master/src/LimitsMiddleware/Limits.MaxRequestContentLength.cs#L71). 

Setting the log_name_ to null [doesn't disable it](https://github.com/damianh/LimitsMiddleware/blob/master/src/LimitsMiddleware/Limits.MaxRequestContentLength.cs#L51-L53). 

Instead, in your logging configuration, 

1. set your logging level to higher than `debug`, or ...
2. ...sink/filter all logs from "LimitsMiddleware.MaxRequestContentLength" (or your own log _name_, if you supply it) to a null logger, or...
3. ... filter out all messages from "LimitsMiddleware.MaxRequestContentLength".

I know this is possible for [Serilog](https://github.com/serilog/serilog/wiki/Configuration-Basics#filters)
